# GitHub Actions İş Akışı: Python Paketini Test Et, Derle ve Yayınla
name: Publish Python Package to PyPI

# Bu iş akışı, yeni bir sürüm etiketi (örn: v0.1.0) push'landığında çalışır.
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  # --- İŞ 1: Paketi Derle ve Test Et ---
  build-and-test:
    name: Build and Test Package
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install dependencies and build package
      run: |
        python -m pip install --upgrade pip build
        python -m build

    - name: Upload artifact for publishing
      uses: actions/upload-artifact@v4
      with:
        name: python-package
        path: ./dist

  # --- İŞ 2: Paketi PyPI'a Yükle ---
  publish-to-pypi:
    name: Publish to PyPI
    # Yalnızca 'build-and-test' işi başarılı olursa çalışır
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Güvenli OIDC bağlantısı için gereklidir

    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: python-package
        path: dist

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}